-- Reference data: production_country

INSERT INTO production_country (country_id, country_name) VALUES ('US', 'United States of America');
INSERT INTO production_country (country_id, country_name) VALUES ('DE', 'Germany');
INSERT INTO production_country (country_id, country_name) VALUES ('GB', 'United Kingdom');
INSERT INTO production_country (country_id, country_name) VALUES ('FR', 'France');
INSERT INTO production_country (country_id, country_name) VALUES ('IT', 'Italy');
INSERT INTO production_country (country_id, country_name) VALUES ('ES', 'Spain');
INSERT INTO production_country (country_id, country_name) VALUES ('CN', 'China');
INSERT INTO production_country (country_id, country_name) VALUES ('AU', 'Australia');
INSERT INTO production_country (country_id, country_name) VALUES ('ZA', 'South Africa');
INSERT INTO production_country (country_id, country_name) VALUES ('CA', 'Canada');
INSERT INTO production_country (country_id, country_name) VALUES ('CH', 'Switzerland');
INSERT INTO production_country (country_id, country_name) VALUES ('BE', 'Belgium');
INSERT INTO production_country (country_id, country_name) VALUES ('JP', 'Japan');
INSERT INTO production_country (country_id, country_name) VALUES ('IR', 'Iran');
INSERT INTO production_country (country_id, country_name) VALUES ('NL', 'Netherlands');
INSERT INTO production_country (country_id, country_name) VALUES ('HK', 'Hong Kong');
INSERT INTO production_country (country_id, country_name) VALUES ('TN', 'Tunisia');
INSERT INTO production_country (country_id, country_name) VALUES ('IE', 'Ireland');
INSERT INTO production_country (country_id, country_name) VALUES ('DO', 'Dominican Republic');
INSERT INTO production_country (country_id, country_name) VALUES ('HR', 'Croatia');
INSERT INTO production_country (country_id, country_name) VALUES ('RU', 'Russia');
INSERT INTO production_country (country_id, country_name) VALUES ('MK', 'Macedonia');
INSERT INTO production_country (country_id, country_name) VALUES ('AT', 'Austria');
INSERT INTO production_country (country_id, country_name) VALUES ('TW', 'Taiwan');
INSERT INTO production_country (country_id, country_name) VALUES ('NZ', 'New Zealand');
INSERT INTO production_country (country_id, country_name) VALUES ('MX', 'Mexico');
INSERT INTO production_country (country_id, country_name) VALUES ('PL', 'Poland');
INSERT INTO production_country (country_id, country_name) VALUES ('PE', 'Peru');
INSERT INTO production_country (country_id, country_name) VALUES ('CU', 'Cuba');
INSERT INTO production_country (country_id, country_name) VALUES ('LI', 'Liechtenstein');
INSERT INTO production_country (country_id, country_name) VALUES ('DK', 'Denmark');
INSERT INTO production_country (country_id, country_name) VALUES ('PT', 'Portugal');
INSERT INTO production_country (country_id, country_name) VALUES ('FI', 'Finland');
INSERT INTO production_country (country_id, country_name) VALUES ('SE', 'Sweden');
INSERT INTO production_country (country_id, country_name) VALUES ('AR', 'Argentina');
INSERT INTO production_country (country_id, country_name) VALUES ('IS', 'Iceland');
INSERT INTO production_country (country_id, country_name) VALUES ('KR', 'South Korea');
INSERT INTO production_country (country_id, country_name) VALUES ('RS', 'Serbia');
INSERT INTO production_country (country_id, country_name) VALUES ('HU', 'Hungary');
INSERT INTO production_country (country_id, country_name) VALUES ('CZ', 'Czech Republic');
INSERT INTO production_country (country_id, country_name) VALUES ('IN', 'India');
INSERT INTO production_country (country_id, country_name) VALUES ('BR', 'Brazil');
INSERT INTO production_country (country_id, country_name) VALUES ('GR', 'Greece');
INSERT INTO production_country (country_id, country_name) VALUES ('CD', 'Congo');
INSERT INTO production_country (country_id, country_name) VALUES ('SN', 'Senegal');
INSERT INTO production_country (country_id, country_name) VALUES ('BF', 'Burkina Faso');
INSERT INTO production_country (country_id, country_name) VALUES ('RO', 'Romania');
INSERT INTO production_country (country_id, country_name) VALUES ('PH', 'Philippines');
INSERT INTO production_country (country_id, country_name) VALUES ('VN', 'Vietnam');
INSERT INTO production_country (country_id, country_name) VALUES ('TT', 'Trinidad and Tobago');
INSERT INTO production_country (country_id, country_name) VALUES ('BG', 'Bulgaria');
INSERT INTO production_country (country_id, country_name) VALUES ('CL', 'Chile');
INSERT INTO production_country (country_id, country_name) VALUES ('NO', 'Norway');
INSERT INTO production_country (country_id, country_name) VALUES ('KZ', 'Kazakhstan');
INSERT INTO production_country (country_id, country_name) VALUES ('DZ', 'Algeria');
INSERT INTO production_country (country_id, country_name) VALUES ('LU', 'Luxembourg');
INSERT INTO production_country (country_id, country_name) VALUES ('GE', 'Georgia');
INSERT INTO production_country (country_id, country_name) VALUES ('UA', 'Ukraine');
INSERT INTO production_country (country_id, country_name) VALUES ('BW', 'Botswana');
INSERT INTO production_country (country_id, country_name) VALUES ('AW', 'Aruba');
INSERT INTO production_country (country_id, country_name) VALUES ('IL', 'Israel');
INSERT INTO production_country (country_id, country_name) VALUES ('TR', 'Turkey');
INSERT INTO production_country (country_id, country_name) VALUES ('EC', 'Ecuador');
INSERT INTO production_country (country_id, country_name) VALUES ('LB', 'Lebanon');
INSERT INTO production_country (country_id, country_name) VALUES ('MA', 'Morocco');
INSERT INTO production_country (country_id, country_name) VALUES ('BA', 'Bosnia and Herzegovina');
INSERT INTO production_country (country_id, country_name) VALUES ('BS', 'Bahamas');
INSERT INTO production_country (country_id, country_name) VALUES ('MY', 'Malaysia');
INSERT INTO production_country (country_id, country_name) VALUES ('BT', 'Bhutan');
INSERT INTO production_country (country_id, country_name) VALUES ('JM', 'Jamaica');
INSERT INTO production_country (country_id, country_name) VALUES ('PK', 'Pakistan');
INSERT INTO production_country (country_id, country_name) VALUES ('NP', 'Nepal');
INSERT INTO production_country (country_id, country_name) VALUES ('CI', 'Cote D''Ivoire');
INSERT INTO production_country (country_id, country_name) VALUES ('TH', 'Thailand');
INSERT INTO production_country (country_id, country_name) VALUES ('NA', 'Namibia');
INSERT INTO production_country (country_id, country_name) VALUES ('CM', 'Cameroon');
INSERT INTO production_country (country_id, country_name) VALUES ('CO', 'Colombia');
INSERT INTO production_country (country_id, country_name) VALUES ('XC', 'Czechoslovakia');
INSERT INTO production_country (country_id, country_name) VALUES ('UY', 'Uruguay');
INSERT INTO production_country (country_id, country_name) VALUES ('SI', 'Slovenia');
INSERT INTO production_country (country_id, country_name) VALUES ('LY', 'Libyan Arab Jamahiriya');
INSERT INTO production_country (country_id, country_name) VALUES ('PR', 'Puerto Rico');
INSERT INTO production_country (country_id, country_name) VALUES ('SU', 'Soviet Union');
INSERT INTO production_country (country_id, country_name) VALUES ('XG', 'East Germany');
INSERT INTO production_country (country_id, country_name) VALUES ('SG', 'Singapore');
INSERT INTO production_country (country_id, country_name) VALUES ('AF', 'Afghanistan');
INSERT INTO production_country (country_id, country_name) VALUES ('MT', 'Malta');
INSERT INTO production_country (country_id, country_name) VALUES ('PA', 'Panama');
INSERT INTO production_country (country_id, country_name) VALUES ('EG', 'Egypt');
INSERT INTO production_country (country_id, country_name) VALUES ('ZW', 'Zimbabwe');
INSERT INTO production_country (country_id, country_name) VALUES ('TJ', 'Tajikistan');
INSERT INTO production_country (country_id, country_name) VALUES ('UZ', 'Uzbekistan');
INSERT INTO production_country (country_id, country_name) VALUES ('CR', 'Costa Rica');
INSERT INTO production_country (country_id, country_name) VALUES ('KW', 'Kuwait');
INSERT INTO production_country (country_id, country_name) VALUES ('MQ', 'Martinique');
INSERT INTO production_country (country_id, country_name) VALUES ('GH', 'Ghana');
INSERT INTO production_country (country_id, country_name) VALUES ('AM', 'Armenia');
INSERT INTO production_country (country_id, country_name) VALUES ('ID', 'Indonesia');
INSERT INTO production_country (country_id, country_name) VALUES ('MN', 'Mongolia');
INSERT INTO production_country (country_id, country_name) VALUES ('BO', 'Bolivia');
INSERT INTO production_country (country_id, country_name) VALUES ('MC', 'Monaco');
INSERT INTO production_country (country_id, country_name) VALUES ('IQ', 'Iraq');
INSERT INTO production_country (country_id, country_name) VALUES ('SK', 'Slovakia');
INSERT INTO production_country (country_id, country_name) VALUES ('CS', 'Serbia and Montenegro');
INSERT INTO production_country (country_id, country_name) VALUES ('VE', 'Venezuela');
INSERT INTO production_country (country_id, country_name) VALUES ('LT', 'Lithuania');
INSERT INTO production_country (country_id, country_name) VALUES ('RW', 'Rwanda');
INSERT INTO production_country (country_id, country_name) VALUES ('PS', 'Palestinian Territory');
INSERT INTO production_country (country_id, country_name) VALUES ('TD', 'Chad');
INSERT INTO production_country (country_id, country_name) VALUES ('PY', 'Paraguay');
INSERT INTO production_country (country_id, country_name) VALUES ('QA', 'Qatar');
INSERT INTO production_country (country_id, country_name) VALUES ('EE', 'Estonia');
INSERT INTO production_country (country_id, country_name) VALUES ('MO', 'Macao');
INSERT INTO production_country (country_id, country_name) VALUES ('ML', 'Mali');
INSERT INTO production_country (country_id, country_name) VALUES ('UM', 'United States Minor Outlying Islands');
INSERT INTO production_country (country_id, country_name) VALUES ('LV', 'Latvia');
INSERT INTO production_country (country_id, country_name) VALUES ('AE', 'United Arab Emirates');
INSERT INTO production_country (country_id, country_name) VALUES ('AZ', 'Azerbaijan');
INSERT INTO production_country (country_id, country_name) VALUES ('KY', 'Cayman Islands');
INSERT INTO production_country (country_id, country_name) VALUES ('NI', 'Nicaragua');
INSERT INTO production_country (country_id, country_name) VALUES ('LR', 'Liberia');
INSERT INTO production_country (country_id, country_name) VALUES ('YU', 'Yugoslavia');
INSERT INTO production_country (country_id, country_name) VALUES ('ME', 'Montenegro');
INSERT INTO production_country (country_id, country_name) VALUES ('AO', 'Angola');
INSERT INTO production_country (country_id, country_name) VALUES ('BY', 'Belarus');
INSERT INTO production_country (country_id, country_name) VALUES ('KH', 'Cambodia');
INSERT INTO production_country (country_id, country_name) VALUES ('MR', 'Mauritania');
INSERT INTO production_country (country_id, country_name) VALUES ('CY', 'Cyprus');
INSERT INTO production_country (country_id, country_name) VALUES ('BD', 'Bangladesh');
INSERT INTO production_country (country_id, country_name) VALUES ('SY', 'Syrian Arab Republic');
INSERT INTO production_country (country_id, country_name) VALUES ('KG', 'Kyrgyz Republic');
INSERT INTO production_country (country_id, country_name) VALUES ('AL', 'Albania');
INSERT INTO production_country (country_id, country_name) VALUES ('TZ', 'Tanzania');
INSERT INTO production_country (country_id, country_name) VALUES ('KP', 'North Korea');
INSERT INTO production_country (country_id, country_name) VALUES ('KE', 'Kenya');
INSERT INTO production_country (country_id, country_name) VALUES ('JO', 'Jordan');
INSERT INTO production_country (country_id, country_name) VALUES ('UG', 'Uganda');
INSERT INTO production_country (country_id, country_name) VALUES ('SA', 'Saudi Arabia');
INSERT INTO production_country (country_id, country_name) VALUES ('SO', 'Somalia');
INSERT INTO production_country (country_id, country_name) VALUES ('GT', 'Guatemala');
INSERT INTO production_country (country_id, country_name) VALUES ('MG', 'Madagascar');
INSERT INTO production_country (country_id, country_name) VALUES ('ET', 'Ethiopia');
INSERT INTO production_country (country_id, country_name) VALUES ('LK', 'Sri Lanka');
INSERT INTO production_country (country_id, country_name) VALUES ('PG', 'Papua New Guinea');
INSERT INTO production_country (country_id, country_name) VALUES ('NG', 'Nigeria');
INSERT INTO production_country (country_id, country_name) VALUES ('LA', 'Lao People''s Democratic Republic');
INSERT INTO production_country (country_id, country_name) VALUES ('PF', 'French Polynesia');
INSERT INTO production_country (country_id, country_name) VALUES ('AN', 'Netherlands Antilles');
INSERT INTO production_country (country_id, country_name) VALUES ('CG', 'Congo');
INSERT INTO production_country (country_id, country_name) VALUES ('MM', 'Myanmar');
INSERT INTO production_country (country_id, country_name) VALUES ('BM', 'Bermuda');
INSERT INTO production_country (country_id, country_name) VALUES ('SV', 'El Salvador');
INSERT INTO production_country (country_id, country_name) VALUES ('TF', 'French Southern Territories');
INSERT INTO production_country (country_id, country_name) VALUES ('WS', 'Samoa');
INSERT INTO production_country (country_id, country_name) VALUES ('MD', 'Moldova');
INSERT INTO production_country (country_id, country_name) VALUES ('BB', 'Barbados');
INSERT INTO production_country (country_id, country_name) VALUES ('AQ', 'Antarctica');
INSERT INTO production_country (country_id, country_name) VALUES ('GI', 'Gibraltar');
INSERT INTO production_country (country_id, country_name) VALUES ('BN', 'Brunei Darussalam');
INSERT INTO production_country (country_id, country_name) VALUES ('HN', 'Honduras');
INSERT INTO production_country (country_id, country_name) VALUES ('GN', 'Guinea');
