-- Reference data: spoken_language

INSERT INTO spoken_language (spoken_language_id, language_name) VALUES ('en', 'English');
INSERT INTO spoken_language (spoken_language_id, language_name) VALUES ('fr', 'Français');
INSERT INTO spoken_language (spoken_language_id, language_name) VALUES ('es', 'Español');
INSERT INTO spoken_language (spoken_language_id, language_name) VALUES ('de', 'Deutsch');
INSERT INTO spoken_language (spoken_language_id, language_name) VALUES ('ru', 'Pусский');
INSERT INTO spoken_language (spoken_language_id, language_name) VALUES ('la', 'Latin');
INSERT INTO spoken_language (spoken_language_id, language_name) VALUES ('nl', 'Nederlands');
INSERT INTO spoken_language (spoken_language_id, language_name) VALUES ('cn', '广州话 / 廣州話');
INSERT INTO spoken_language (spoken_language_id, language_name) VALUES ('zh', '普通话');
INSERT INTO spoken_language (spoken_language_id, language_name) VALUES ('hu', 'Magyar');
INSERT INTO spoken_language (spoken_language_id, language_name) VALUES ('sq', 'shqip');
INSERT INTO spoken_language (spoken_language_id, language_name) VALUES ('it', 'Italiano');
INSERT INTO spoken_language (spoken_language_id, language_name) VALUES ('ko', '한국어/조선말');
INSERT INTO spoken_language (spoken_language_id, language_name) VALUES ('fa', 'فارسی');
INSERT INTO spoken_language (spoken_language_id, language_name) VALUES ('da', 'Dansk');
INSERT INTO spoken_language (spoken_language_id, language_name) VALUES ('ja', '日本語');
INSERT INTO spoken_language (spoken_language_id, language_name) VALUES ('ar', 'العربية');
INSERT INTO spoken_language (spoken_language_id, language_name) VALUES ('hr', 'Hrvatski');
INSERT INTO spoken_language (spoken_language_id, language_name) VALUES ('bs', 'Bosanski');
INSERT INTO spoken_language (spoken_language_id, language_name) VALUES ('ro', 'Română');
INSERT INTO spoken_language (spoken_language_id, language_name) VALUES ('id', 'Bahasa indonesia');
INSERT INTO spoken_language (spoken_language_id, language_name) VALUES ('ms', 'Bahasa melayu');
INSERT INTO spoken_language (spoken_language_id, language_name) VALUES ('sv', 'svenska');
INSERT INTO spoken_language (spoken_language_id, language_name) VALUES ('he', 'עִבְרִית');
INSERT INTO spoken_language (spoken_language_id, language_name) VALUES ('cs', 'Český');
INSERT INTO spoken_language (spoken_language_id, language_name) VALUES ('pl', 'Polski');
INSERT INTO spoken_language (spoken_language_id, language_name) VALUES ('ga', 'Gaeilge');
INSERT INTO spoken_language (spoken_language_id, language_name) VALUES ('no', 'Norsk');
INSERT INTO spoken_language (spoken_language_id, language_name) VALUES ('sk', 'Slovenčina');
INSERT INTO spoken_language (spoken_language_id, language_name) VALUES ('vi', 'Tiếng Việt');
INSERT INTO spoken_language (spoken_language_id, language_name) VALUES ('pt', 'Português');
INSERT INTO spoken_language (spoken_language_id, language_name) VALUES ('hi', 'हिन्दी');
INSERT INTO spoken_language (spoken_language_id, language_name) VALUES ('ca', 'Català');
INSERT INTO spoken_language (spoken_language_id, language_name) VALUES ('is', 'Íslenska');
INSERT INTO spoken_language (spoken_language_id, language_name) VALUES ('af', 'Afrikaans');
INSERT INTO spoken_language (spoken_language_id, language_name) VALUES ('sr', 'Srpski');
INSERT INTO spoken_language (spoken_language_id, language_name) VALUES ('bn', 'বাংলা');
INSERT INTO spoken_language (spoken_language_id, language_name) VALUES ('wo', 'Wolof');
INSERT INTO spoken_language (spoken_language_id, language_name) VALUES ('cy', 'Cymraeg');
INSERT INTO spoken_language (spoken_language_id, language_name) VALUES ('th', 'ภาษาไทย');
INSERT INTO spoken_language (spoken_language_id, language_name) VALUES ('lv', 'Latviešu');
INSERT INTO spoken_language (spoken_language_id, language_name) VALUES ('sw', 'Kiswahili');
INSERT INTO spoken_language (spoken_language_id, language_name) VALUES ('bg', 'български език');
INSERT INTO spoken_language (spoken_language_id, language_name) VALUES ('el', 'ελληνικά');
INSERT INTO spoken_language (spoken_language_id, language_name) VALUES ('tr', 'Türkçe');
INSERT INTO spoken_language (spoken_language_id, language_name) VALUES ('fi', 'suomi');
INSERT INTO spoken_language (spoken_language_id, language_name) VALUES ('eo', 'Esperanto');
INSERT INTO spoken_language (spoken_language_id, language_name) VALUES ('uk', 'Український');
INSERT INTO spoken_language (spoken_language_id, language_name) VALUES ('ka', 'ქართული');
INSERT INTO spoken_language (spoken_language_id, language_name) VALUES ('nb', 'Bokmål');
INSERT INTO spoken_language (spoken_language_id, language_name) VALUES ('xx', 'No Language');
INSERT INTO spoken_language (spoken_language_id, language_name) VALUES ('eu', 'euskera');
INSERT INTO spoken_language (spoken_language_id, language_name) VALUES ('az', 'Azərbaycan');
INSERT INTO spoken_language (spoken_language_id, language_name) VALUES ('mt', 'Malti');
INSERT INTO spoken_language (spoken_language_id, language_name) VALUES ('ur', 'اردو');
INSERT INTO spoken_language (spoken_language_id, language_name) VALUES ('zu', 'isiZulu');
INSERT INTO spoken_language (spoken_language_id, language_name) VALUES ('bm', 'Bamanankan');
INSERT INTO spoken_language (spoken_language_id, language_name) VALUES ('ps', 'پښتو');
INSERT INTO spoken_language (spoken_language_id, language_name) VALUES ('so', 'Somali');
INSERT INTO spoken_language (spoken_language_id, language_name) VALUES ('pa', 'ਪੰਜਾਬੀ');
INSERT INTO spoken_language (spoken_language_id, language_name) VALUES ('be', 'беларуская мова');
INSERT INTO spoken_language (spoken_language_id, language_name) VALUES ('ta', 'தமிழ்');
INSERT INTO spoken_language (spoken_language_id, language_name) VALUES ('gl', 'Galego');
INSERT INTO spoken_language (spoken_language_id, language_name) VALUES ('rw', 'Kinyarwanda');
INSERT INTO spoken_language (spoken_language_id, language_name) VALUES ('kk', 'қазақ');
INSERT INTO spoken_language (spoken_language_id, language_name) VALUES ('et', 'Eesti');
INSERT INTO spoken_language (spoken_language_id, language_name) VALUES ('lt', 'Lietuvikai');
INSERT INTO spoken_language (spoken_language_id, language_name) VALUES ('sl', 'Slovenščina');
INSERT INTO spoken_language (spoken_language_id, language_name) VALUES ('te', 'తెలుగు');
INSERT INTO spoken_language (spoken_language_id, language_name) VALUES ('ff', 'Fulfulde');
INSERT INTO spoken_language (spoken_language_id, language_name) VALUES ('uz', 'ozbek');
INSERT INTO spoken_language (spoken_language_id, language_name) VALUES ('ha', 'Hausa');
